### ISSUE TITLE
Error in 2_extract_files.py

### ISSUE THREAD

**Issue by kousik97** [harvitronix/five-video-classification-methods#10]
Got the below error while trying execute 2_extract_files.py:
Traceback (most recent call last):
  File "2_extract_files.py", line 99, in <module>
    main()
  File "2_extract_files.py", line 96, in main
    extract_files()
  File "2_extract_files.py", line 50, in extract_files
    call(["ffmpeg", "-i", src, dest])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by moonikwe** [comment]
How was this problem solved? I'm experiencing the same thing

**Comment by ShaoNeilz** [comment]
@kousik97  Hi, did you solve it?  I am also worry about this problem. Thank you for your help
