### ISSUE TITLE
 list index out of range error on Windows 10, Python

### ISSUE THREAD

**Issue by Sharma-Prachi** [harvitronix/five-video-classification-methods#117]
Hi!
I am not able to go through this error. 
Traceback (most recent call last):
  File "1_move_files.py", line 81, in <module>
    main()
  File "1_move_files.py", line 78, in main
    move_files(group_lists)
  File "1_move_files.py", line 49, in move_files
    filename = parts[1]
IndexError: list index out of range

I have tried every suggestion to solve it in other similar issues. 
I tried parts = video.split('\\'). but didn't change a thing. I have all the files in the same directory I am working in. 
I tried installing ffmpeg but it also didn't help.

I am working on Windows 10 and Anaconda. Please help me solve this issue as I am not able to code further.

Thanks in advance!

**Comment by ElliotWood** [comment]
Change it to
`parts = os.path.split(video)`
