### ISSUE TITLE
Getting error in extract_features.py

### ISSUE THREAD

**Issue by preetigupta010203** [harvitronix/five-video-classification-methods#143]
Hi, I ran the 1_move_files.py and 2_extract_files.py successfully.
after that, I tried running the extract_features.py, it gives me the following error

  File "C:\Users\Preeti Gupta\Downloads\five-video-classification-methods-master\data.py", line 81, in get_classes
    if item[1] not in classes:

IndexError: list index out of range

**Comment by JGL22** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "extract_features.py", line 25, in <module>
    data = DataSet(seq_length=seq_length, class_limit=class_limit)
  File "C:\Users\jg2020\anaconda3\envs\tfgpu1\Lib\site-packages\tensorflow\models\data.py", line 50, in __init__
    self.classes = self.get_classes()
  File "C:\Users\jg2020\anaconda3\envs\tfgpu1\Lib\site-packages\tensorflow\models\data.py", line 82, in get_classes
    if item[1] not in classes:
IndexError: list index out of range

I have same error when running the extract_features.py
Can anyone explain about the "classes"?

**Comment by farhantandia** [comment]
I also have this issue. how you handle it guys @JGL22 @preetigupta010203 ??

**Comment by hyuDev** [comment]
check your data/data.csv.
right format csv have not empty line(row)
if your csv file have empty row, change  open("path","w") to open("path","w",newline="\n")
