### ISSUE TITLE
error running 2_extract_files.py

### ISSUE THREAD

**Issue by anujshah1003** [harvitronix/five-video-classification-methods#15]
when i run 2_extract_files.py

i get this : extracted and wrote 0 video files

**Comment by SamvitJ** [comment]
I'm running into the following error after running`python 1_move_files.py` and then trying `python 2_extract_files.py`:
`user$ python 2_extract_files.py
Traceback (most recent call last):
  File "2_extract_files.py", line 99, in <module>
    main()
  File "2_extract_files.py", line 96, in main
    extract_files()
  File "2_extract_files.py", line 50, in extract_files
    call(["ffmpeg", "-i", src, dest])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

**Comment by harvitronix** [comment]
@anujshah1003 Did you extract the rar file with `unrar e UCF101.rar` first?
