### ISSUE TITLE
"ffmpeg" should be listed as a required installation

### ISSUE THREAD

**Issue by SamvitJ** [harvitronix/five-video-classification-methods#16]
"ffmpeg" should be listed as a required installation.
Otherwise, 2_extract_files.py fails to run

**Comment by SamvitJ** [comment]
FYI: installing ffmpeg is the solution to the following error

user-me$ python 2_extract_files.py
Traceback (most recent call last):
File "2_extract_files.py", line 99, in 
main()
File "2_extract_files.py", line 96, in main
extract_files()
File "2_extract_files.py", line 50, in extract_files
call(["ffmpeg", "-i", src, dest])
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
return Popen(*popenargs, **kwargs).wait()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by cagbal** [comment]
Yeah, it should be listed as a requirement.

**Comment by harvitronix** [comment]
Thanks @SamvitJ, done.

**Comment by praneethbellamkonda** [comment]
Thanks @SamvitJ
