### ISSUE TITLE
2_extract_files.py not working

### ISSUE THREAD

**Issue by moonikwe** [harvitronix/five-video-classification-methods#35]
When I run python 2_extract_files.py, this is what I get: 

Traceback (most recent call last):
  File "2_extract_files.py", line 99, in <module>
    main()
  File "2_extract_files.py", line 96, in main
    extract_files()
  File "2_extract_files.py", line 38, in extract_files
    video_parts = get_video_parts(video_path)
  File "2_extract_files.py", line 76, in get_video_parts
    filename = parts[3]
IndexError: list index out of range

I already have ffmpeg installed and added it to my system path. What could be wrong?

**Comment by harvitronix** [comment]
What gets returned if you print `video_parts` and `video_path`? Looks like `get_video_parts()` isn't returning the parts properly.

Are you on Windows by chance?

**Comment by moonikwe** [comment]
It is getting the correct video_path it shows this in get_video_path function
video_path in get_video_parts() ./train\ApplyEyeMakeup\v_ApplyEyeMakeup_g08_c01.avi
Traceback (most recent call last):
  File "2_extract_files.py", line 109, in <module>
    main()
  File "2_extract_files.py", line 106, in main
    extract_files()
  File "2_extract_files.py", line 39, in extract_files
    video_parts = get_video_parts(video_path)
  File "2_extract_files.py", line 80, in get_video_parts
    filename = parts[3]
IndexError: list index out of range

yes, I am using windows

**Comment by harvitronix** [comment]
It may be as simple as changing the file separator in the `2_extract_files.py` file. Take a look here: https://github.com/harvitronix/five-video-classification-methods/blob/master/data/2_extract_files.py#L75

It's splitting on the `/` character, whereas your Windows path uses `\` as the separator. So changing that slash should do the trick.

**Comment by moonikwe** [comment]
I see. It worked, thanks!
