### ISSUE TITLE
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

### ISSUE THREAD

**Issue by rlgalvez** [harvitronix/five-video-classification-methods#47]
Im running the train.py but got the following errors,

Using TensorFlow backend.
Loading LSTM model.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 2048)              33562624  
_________________________________________________________________
dense_1 (Dense)              (None, 512)               1049088   
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 1026      
=================================================================
Total params: 34,612,738
Trainable params: 34,612,738
Non-trainable params: 0
_________________________________________________________________
None
2017-11-26 16:12:57.413854: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Creating train generator with 20 samples.
Epoch 1/2
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\utils\data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
  File "D:\Pycharm Projects\CPU\VideoClassificationDemo\data.py", line 25, in __next__
    return next(self.iterator)
  File "D:\Pycharm Projects\CPU\VideoClassificationDemo\data.py", line 191, in frame_generator
    y.append(self.get_class_one_hot(sample[1]))
  File "D:\Pycharm Projects\CPU\VideoClassificationDemo\data.py", line 103, in get_class_one_hot
    assert len(label_hot) == len(self.classes)
AssertionError

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\utils\data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
  File "D:\Pycharm Projects\CPU\VideoClassificationDemo\data.py", line 25, in __next__
    return next(self.iterator)
StopIteration

Traceback (most recent call last):
  File "D:/Pycharm Projects/CPU/VideoClassificationDemo/train.py", line 110, in <module>
    main()
  File "D:/Pycharm Projects/CPU/VideoClassificationDemo/train.py", line 107, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "D:/Pycharm Projects/CPU/VideoClassificationDemo/train.py", line 81, in train
    workers=4)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\models.py", line 1117, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Reagan\AppData\Local\Continuum\Anaconda3\envs\keras2\lib\site-packages\keras\engine\training.py", line 1877, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

Process finished with exit code 1

**Comment by rlgalvez** [comment]
Solved the problem by upgrading keras.
