### ISSUE TITLE
error while running 1_move_files.py

### ISSUE THREAD

**Issue by yoyo220** [harvitronix/five-video-classification-methods#49]
When I run python 1_move_files.py, i get : 

Traceback (most recent call last):
  File "1_move_files.py", line 81, in <module>
    main()
  File "1_move_files.py", line 78, in main
    move_files(group_lists)
  File "1_move_files.py", line 49, in move_files
    filename = parts[1]
IndexError: list index out of range

Is there anything i did wrong ?

**Comment by harvitronix** [comment]
Hmm looks like your file path wasn't properly split. Can you print the value of `parts` at line 48?

**Comment by yoyo220** [comment]
line 46:            # Get the parts.
line 47:            parts = video.split(os.path.sep)
line 48             classname = parts[0]
line 49:            filename = parts[1]


this is how the videos files looks like when i extract it with "unrar e UCF101.rar"
![capture](https://user-images.githubusercontent.com/34432836/33915772-0998ccba-dfe0-11e7-8bbd-7e55aac346c1.PNG)

**Comment by harvitronix** [comment]
Looks right. Can you add a line between 47 and 48 that is just:

`print(parts)`

And let me know what it prints?

**Comment by yoyo220** [comment]
it now prints : 

['ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi']
Traceback (most recent call last):
  File "1_move_files.py", line 82, in <module>
    main()
  File "1_move_files.py", line 79, in main
    move_files(group_lists)
  File "1_move_files.py", line 50, in move_files
    filename = parts[1]
IndexError: list index out of range


or sometimes : 

Traceback (most recent call last):
['ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi']
  File "C:/Users/Gary/Desktop/five-video-classification-methods-master/data/1_move_files.py", line 82, in <module>
    main()
  File "C:/Users/Gary/Desktop/five-video-classification-methods-master/data/1_move_files.py", line 79, in main
    move_files(group_lists)
  File "C:/Users/Gary/Desktop/five-video-classification-methods-master/data/1_move_files.py", line 50, in move_files
    filename = parts[1]
IndexError: list index out of range

**Comment by ord1991** [comment]
Hi
Im having the same issue.
Did you manage to fix this?
thank you.

**Comment by ord1991** [comment]
Hi
Solved it myself.
changed:
`parts = video.split(os.path.sep)`
to:
`parts = video.split('/')`
