### ISSUE TITLE
TypeError: instance has no next() method

### ISSUE THREAD

**Issue by FelicityLeung** [harvitronix/five-video-classification-methods#53]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
Traceback (most recent call last):
  File "/home/a504/pycharm-community-2017.2.4/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/a504/pycharm-community-2017.2.4/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/a504/PycharmProjects/keras_LRCN/train.py", line 111, in <module>
    main()
  File "/home/a504/PycharmProjects/keras_LRCN/train.py", line 108, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "/home/a504/PycharmProjects/keras_LRCN/train.py", line 82, in train
    workers=4)#表示使用线程数
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 1223, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2083, in fit_generator
    generator_output = next(output_generator)
StopIteration

I prepare the data and run train.py using LRCN model ,but it just get this error.I am new in this and don't know how to debug.I would very appreciate if someone could help.

**Comment by TheGalileo** [comment]
I was able to reproduce your error. Let's wait for @harvitronix to comment on that. But for now, if you want to get going, you can set `load_to_memory` in `train.py` (Line 91) to `True`. Disclaimer: this will take additional memory, for obvious reasons.

**Comment by FelicityLeung** [comment]
Actually,I have found the solution in stackoverflow,but I am to busy to post here.This is the solution web https://stackoverflow.com/questions/5982817/problems-using-next-method-in-python.
If you get this solution and still get this error ,maybe it is because your image root is wrong which make the image can't be read into the array.

**Comment by BrownOfSummer** [comment]
As the solution of @FelicityLeung , I modify the 23th line in data.py: **def__next(self)__** to **def next(self)**, and it works well in python2.7.10

**Comment by moonikwe** [comment]
Hi I'm having this error

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in
 _bootstrap_inner
    self.run()
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in
 run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\d
ata_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\data.py", line 25, in __n
ext__
    return next(self.iterator)
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\data.py", line 191, in fr
ame_generator
    y.append(self.get_class_one_hot(sample[1]))
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\data.py", line 103, in ge
t_class_one_hot
    assert len(label_hot) == len(self.classes)
AssertionError

Traceback (most recent call last):
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\train.py", line 110, in <
module>
    main()
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\train.py", line 107, in m
ain
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "C:\Users\Munic\Documents\Popping-Dance-Style-Classification\train.py", line 81, in tr
ain
    workers=4)
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\
interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\models.
py", line 1156, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\
interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Munic\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\
training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration

I'd like to ask what could have went wrong. Btw, I am using python 3.6.3.

**Comment by swaticolab** [comment]
Hello,
Did anybody find a solution to this, for python 3?
Any help would be appreciated.

**Comment by gaurav22verma** [comment]
> I was able to reproduce your error. Let's wait for @harvitronix to comment on that. But for now, if you want to get going, you can set `load_to_memory` in `train.py` (Line 91) to `True`. Disclaimer: this will take additional memory, for obvious reasons.

Does this seem to help for now?

**Comment by tatarize** [comment]
If you hit this error just assign the missing next function to the python3 function:
``            next = __next__``
