### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by ramanandh25** [harvitronix/five-video-classification-methods#57]
hi i am getting the following error when running the extract_ file .py

Traceback (most recent call last):
  File "2_extract_files.py", line 98, in <module>
    main()
  File "2_extract_files.py", line 95, in main
    extract_files()
  File "2_extract_files.py", line 49, in extract_files
    call(['ffmpeg', "-i", src, dest])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by reynierhdez** [comment]
You should install FFmpeg.
If you are working on ubuntu, try to install it using apt, following these instructions: [How to install FFmpeg on Ubuntu 14.04](https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/)

**Comment by harvitronix** [comment]
And if you have ffmpeg installed, make sure it's available in your path. Or you can change line 49 in `2_extract_files.py` to use the absolute path to ffmpeg.

**Comment by ramanandh25** [comment]
thanks i have solved the problem
