### ISSUE TITLE
error in training the c3d model

### ISSUE THREAD

**Issue by milkcat0904** [harvitronix/five-video-classification-methods#59]
hi, thx for your codes,
sry to interrupt
I got the error when training the c3d model(another 4 models is fine)

`Traceback (most recent call last):
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 110, in <module>
    main()
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 107, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 81, in train
    workers=4)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/models.py", line 1227, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2147, in fit_generator
    class_weight=class_weight)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1839, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,64,40,40,40]
	 [[Node: training/Adam/gradients/pool1/MaxPool3D_grad/MaxPool3DGrad = MaxPool3DGrad[T=DT_FLOAT, TInput=DT_FLOAT, _class=["loc:@pool1/MaxPool3D"], data_format="NDHWC", ksize=[1, 1, 2, 2, 1], padding="VALID", strides=[1, 1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1/Relu, pool1/MaxPool3D, training/Adam/gradients/conv2/convolution_grad/Conv3DBackpropInputV2)]]

Caused by op 'training/Adam/gradients/pool1/MaxPool3D_grad/MaxPool3DGrad', defined at:
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 110, in <module>
    main()
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 107, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "/home/catidog/work/action_recognition/five-video-classification-methods/train.py", line 81, in train
    workers=4)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/models.py", line 1227, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2016, in fit_generator
    self._make_train_function()
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 415, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 73, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2394, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 155, in _MaxPool3DGrad
    data_format=op.get_attr("data_format"))
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2939, in _max_pool3d_grad
    data_format=data_format, name=name)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/catidog/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access`

plz give me some advice,thx a lot

**Comment by harvitronix** [comment]
@milkcat0904 You're out of GPU memory I believe. Same thing happens to me when I run it on my local GPU. I need to use a bigger, 12GB GPU for it to run properly.
