### ISSUE TITLE
ValueError: output of generator should be tuple '(x, y, sample_weight)' or (x, y) but found : None

### ISSUE THREAD

**Issue by RadhikaaM** [harvitronix/five-video-classification-methods#85]
I am using train.py with AFEW dataset (having seven classes of facial expression). I have extracted the feature with extractor.py and train.py is working fine when load_to_memory=True (i.e without generators) but it's throwing an error when setting  load_to_memory=False. That means the problem is with generators.

Please look into it and help me in fixing it.
 
![d](https://user-images.githubusercontent.com/30682585/39008485-6d0bb370-4426-11e8-8493-de061bbb1cb2.PNG)

**Comment by harvitronix** [comment]
This is usually the error that appears when there's an issue _within_ the generator, and the actual error is usually earlier in the stack track. If you want to copy/paste your entire stack trace, it will be easier to find the issue.

**Comment by RadhikaaM** [comment]
Thanks a lot for the reply.

Here is the traceback :
In [5]: runfile('/home/16mcmi17/Work/five-video-classification-methods-master/train.py', wdir='/home/16mcmi17/Work/five-video-classification-methods-master')

Reloaded modules: processor, data, extractor

Loading LSTM model.

_________________________________________________________________

Layer (type) Output Shape Param #

=================================================================

lstm_1 (LSTM) (None, 2048) 33562624

_________________________________________________________________

dense_3 (Dense) (None, 512) 1049088

_________________________________________________________________

dropout_1 (Dropout) (None, 512) 0

_________________________________________________________________

dense_4 (Dense) (None, 7) 3591

=================================================================

Total params: 34,615,303

Trainable params: 34,615,303

Non-trainable params: 0

_________________________________________________________________

None

Epoch 1/1000

Exception in thread Thread-102:

Traceback (most recent call last):

File "/home/16mcmi17/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner

self.run()

File "/home/16mcmi17/miniconda2/lib/python2.7/threading.py", line 754, in run

self.__target(*self.__args, **self.__kwargs)

File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 612, in data_generator_task

generator_output = next(self._generator)

TypeError: instance has no next() method



Traceback (most recent call last):



File "<ipython-input-5-9f7e148590ba>", line 1, in <module>

runfile('/home/16mcmi17/Work/five-video-classification-methods-master/train.py', wdir='/home/16mcmi17/Work/five-video-classification-methods-master')



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile

execfile(filename, namespace)



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 93, in execfile

builtins.execfile(filename, *where)



File "/home/16mcmi17/Work/five-video-classification-methods-master/train.py", line 110, in <module>

main()



File "/home/16mcmi17/Work/five-video-classification-methods-master/train.py", line 107, in main

load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)



File "/home/16mcmi17/Work/five-video-classification-methods-master/train.py", line 81, in train

workers=4)



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper

return func(*args, **kwargs)



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/keras/models.py", line 1124, in fit_generator

initial_epoch=initial_epoch)



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper

return func(*args, **kwargs)



File "/home/16mcmi17/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1877, in fit_generator

str(generator_output))



ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

**Comment by harvitronix** [comment]
Okay, here's the real error: `TypeError: instance has no next() method`

This is usually caused by running with Python 2.x. If you can, run with Python 3.x, or see here: https://stackoverflow.com/questions/5982817/problems-using-next-method-in-python

**Comment by RadhikaaM** [comment]
Thanks! It worked.
I executed it in python3.6 with tensorflow-gpu 1.4 and it worked.
