### ISSUE TITLE
Training error！！！

### ISSUE THREAD

**Issue by yangjunXTU** [harvitronix/five-video-classification-methods#86]
when I run train.py ，I get error, How can i solve it?

Traceback (most recent call last):
  File "train.py", line 110, in <module>
    main()
  File "train.py", line 107, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train.py", line 81, in train
    workers=4)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/models.py", line 1276, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/yj/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
TypeError: instance has no next() method

**Comment by harvitronix** [comment]
Sorry, the code does not support Python 2.7 very well. See here: https://stackoverflow.com/questions/5982817/problems-using-next-method-in-python

**Comment by yangjunXTU** [comment]
yes，This problem is solved, thank you！！
